package main

func TankSeriesInit() {
	TankKinds = map[BaseItemID]TankSeries{
		TankKind1: {
			TankKind: "雷霆",
			KindID:   TankKind1,
			Levels: map[BaseItemID]TankLevel{
				Level1: {
					Level:      1,
					SubFrameID: Level1,
					EquipSlot:  EquipMainGun,
					Cooldown:   3,
					Hp:         20,
					Damage:     5,
					Speed:      4,
				},
				Level2: {
					Level:      2,
					SubFrameID: Level2,
					Cooldown:   3,
					EquipSlot:  EquipMainGun | EquipEngine,
					Hp:         30,
					Damage:     8,
					Speed:      5,
				},
				Level3: {
					Level:      3,
					SubFrameID: Level3,
					Cooldown:   2,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor,
					Hp:         35,
					Damage:     10,
					Speed:      6,
				},
				Level4: {
					Level:      4,
					SubFrameID: Level4,
					Cooldown:   2,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor,
					Hp:         40,
					Damage:     12,
					Speed:      6,
				},
				Level5: {
					Level:      5,
					SubFrameID: Level3,
					Cooldown:   1,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor | EquipShip,
					Hp:         50,
					Damage:     15,
					Speed:      6,
				},
			},
			FrameImgs: map[BaseItemID]string{
				TankKind1 | Level1 | MoveUp:                                                              "./assets/tank/tank_1/level_1_000000000000_up.png",
				TankKind1 | Level1 | MoveUp | Fire:                                                       "./assets/tank/tank_1/level_1_000000000000_up_fire.png",
				TankKind1 | Level1 | EquipMainGun | MoveUp:                                               "./assets/tank/tank_1/level_1_000000000001_up.png",
				TankKind1 | Level1 | EquipMainGun | MoveUp | Fire:                                        "./assets/tank/tank_1/level_1_000000000001_up_fire.png",
				TankKind1 | Level2 | MoveUp:                                                              "./assets/tank/tank_1/level_2_000000000000_up.png",
				TankKind1 | Level2 | MoveUp | Fire:                                                       "./assets/tank/tank_1/level_2_000000000000_up_fire.png",
				TankKind1 | Level2 | EquipMainGun | MoveUp:                                               "./assets/tank/tank_1/level_2_000000000001_up.png",
				TankKind1 | Level2 | EquipMainGun | MoveUp | Fire:                                        "./assets/tank/tank_1/level_2_000000000001_up_fire.png",
				TankKind1 | Level2 | EquipEngine | MoveUp:                                                "./assets/tank/tank_1/level_2_000000000010_up.png",
				TankKind1 | Level2 | EquipEngine | MoveUp | Fire:                                         "./assets/tank/tank_1/level_2_000000000010_up_fire.png",
				TankKind1 | Level2 | EquipMainGun | EquipEngine | MoveUp:                                 "./assets/tank/tank_1/level_2_000000000011_up.png",
				TankKind1 | Level2 | EquipMainGun | EquipEngine | MoveUp | Fire:                          "./assets/tank/tank_1/level_2_000000000011_up_fire.png",
				TankKind1 | Level3 | MoveUp:                                                              "./assets/tank/tank_1/level_3_000000000000_up.png",
				TankKind1 | Level3 | MoveUp | Fire:                                                       "./assets/tank/tank_1/level_3_000000000000_up_fire.png",
				TankKind1 | Level3 | EquipMainGun | MoveUp:                                               "./assets/tank/tank_1/level_3_000000000001_up.png",
				TankKind1 | Level3 | EquipMainGun | MoveUp | Fire:                                        "./assets/tank/tank_1/level_3_000000000001_up_fire.png",
				TankKind1 | Level3 | EquipEngine | MoveUp:                                                "./assets/tank/tank_1/level_3_000000000010_up.png",
				TankKind1 | Level3 | EquipEngine | MoveUp | Fire:                                         "./assets/tank/tank_1/level_3_000000000010_up_fire.png",
				TankKind1 | Level3 | EquipArmor | MoveUp:                                                 "./assets/tank/tank_1/level_3_000000000100_up.png",
				TankKind1 | Level3 | EquipArmor | MoveUp | Fire:                                          "./assets/tank/tank_1/level_3_000000000100_up_fire.png",
				TankKind1 | Level3 | EquipMainGun | EquipEngine | MoveUp:                                 "./assets/tank/tank_1/level_3_000000000011_up.png",
				TankKind1 | Level3 | EquipMainGun | EquipEngine | MoveUp | Fire:                          "./assets/tank/tank_1/level_3_000000000011_up_fire.png",
				TankKind1 | Level3 | EquipMainGun | EquipArmor | MoveUp:                                  "./assets/tank/tank_1/level_3_000000000101_up.png",
				TankKind1 | Level3 | EquipMainGun | EquipArmor | MoveUp | Fire:                           "./assets/tank/tank_1/level_3_000000000101_up_fire.png",
				TankKind1 | Level3 | EquipArmor | EquipEngine | MoveUp:                                   "./assets/tank/tank_1/level_3_000000000110_up.png",
				TankKind1 | Level3 | EquipArmor | EquipEngine | MoveUp | Fire:                            "./assets/tank/tank_1/level_3_000000000110_up_fire.png",
				TankKind1 | Level3 | EquipMainGun | EquipEngine | EquipArmor | MoveUp:                    "./assets/tank/tank_1/level_3_000000000111_up.png",
				TankKind1 | Level3 | EquipMainGun | EquipEngine | EquipArmor | MoveUp | Fire:             "./assets/tank/tank_1/level_3_000000000111_up_fire.png",
				TankKind1 | Level4 | MoveUp:                                                              "./assets/tank/tank_1/level_4_000000000000_up.png",
				TankKind1 | Level4 | MoveUp | Fire:                                                       "./assets/tank/tank_1/level_4_000000000000_up_fire.png",
				TankKind1 | Level4 | EquipMainGun | MoveUp:                                               "./assets/tank/tank_1/level_4_000000000001_up.png",
				TankKind1 | Level4 | EquipMainGun | MoveUp | Fire:                                        "./assets/tank/tank_1/level_4_000000000001_up_fire.png",
				TankKind1 | Level4 | EquipEngine | MoveUp:                                                "./assets/tank/tank_1/level_4_000000000010_up.png",
				TankKind1 | Level4 | EquipEngine | MoveUp | Fire:                                         "./assets/tank/tank_1/level_4_000000000010_up_fire.png",
				TankKind1 | Level4 | EquipArmor | MoveUp:                                                 "./assets/tank/tank_1/level_4_000000000100_up.png",
				TankKind1 | Level4 | EquipArmor | MoveUp | Fire:                                          "./assets/tank/tank_1/level_4_000000000100_up_fire.png",
				TankKind1 | Level4 | EquipMainGun | EquipEngine | MoveUp:                                 "./assets/tank/tank_1/level_4_000000000011_up.png",
				TankKind1 | Level4 | EquipMainGun | EquipEngine | MoveUp | Fire:                          "./assets/tank/tank_1/level_4_000000000011_up_fire.png",
				TankKind1 | Level4 | EquipMainGun | EquipArmor | MoveUp:                                  "./assets/tank/tank_1/level_4_000000000101_up.png",
				TankKind1 | Level4 | EquipMainGun | EquipArmor | MoveUp | Fire:                           "./assets/tank/tank_1/level_4_000000000101_up_fire.png",
				TankKind1 | Level4 | EquipArmor | EquipEngine | MoveUp:                                   "./assets/tank/tank_1/level_4_000000000110_up.png",
				TankKind1 | Level4 | EquipArmor | EquipEngine | MoveUp | Fire:                            "./assets/tank/tank_1/level_4_000000000110_up_fire.png",
				TankKind1 | Level4 | EquipMainGun | EquipEngine | EquipArmor | MoveUp:                    "./assets/tank/tank_1/level_4_000000000111_up.png",
				TankKind1 | Level4 | EquipMainGun | EquipEngine | EquipArmor | MoveUp | Fire:             "./assets/tank/tank_1/level_4_000000000111_up_fire.png",
				TankKind1 | Level5 | MoveUp:                                                              "./assets/tank/tank_1/level_5_000000000000_up.png",
				TankKind1 | Level5 | MoveUp | Fire:                                                       "./assets/tank/tank_1/level_5_000000000000_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | MoveUp:                                               "./assets/tank/tank_1/level_5_000000000001_up.png",
				TankKind1 | Level5 | EquipMainGun | MoveUp | Fire:                                        "./assets/tank/tank_1/level_5_000000000001_up_fire.png",
				TankKind1 | Level5 | EquipEngine | MoveUp:                                                "./assets/tank/tank_1/level_5_000000000010_up.png",
				TankKind1 | Level5 | EquipEngine | MoveUp | Fire:                                         "./assets/tank/tank_1/level_5_000000000010_up_fire.png",
				TankKind1 | Level5 | EquipArmor | MoveUp:                                                 "./assets/tank/tank_1/level_5_000000000100_up.png",
				TankKind1 | Level5 | EquipArmor | MoveUp | Fire:                                          "./assets/tank/tank_1/level_5_000000000100_up_fire.png",
				TankKind1 | Level5 | EquipShip | MoveUp:                                                  "./assets/tank/tank_1/level_5_000000001000_up.png",
				TankKind1 | Level5 | EquipShip | MoveUp | Fire:                                           "./assets/tank/tank_1/level_5_000000001000_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | MoveUp:                                 "./assets/tank/tank_1/level_5_000000000011_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | MoveUp | Fire:                          "./assets/tank/tank_1/level_5_000000000011_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipArmor | MoveUp:                                  "./assets/tank/tank_1/level_5_000000000101_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipArmor | MoveUp | Fire:                           "./assets/tank/tank_1/level_5_000000000101_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipShip | MoveUp:                                   "./assets/tank/tank_1/level_5_000000001001_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipShip | MoveUp | Fire:                            "./assets/tank/tank_1/level_5_000000001001_up_fire.png",
				TankKind1 | Level5 | EquipArmor | EquipEngine | MoveUp:                                   "./assets/tank/tank_1/level_5_000000000110_up.png",
				TankKind1 | Level5 | EquipArmor | EquipEngine | MoveUp | Fire:                            "./assets/tank/tank_1/level_5_000000000110_up_fire.png",
				TankKind1 | Level5 | EquipEngine | EquipShip | MoveUp:                                    "./assets/tank/tank_1/level_5_000000001010_up.png",
				TankKind1 | Level5 | EquipEngine | EquipShip | MoveUp | Fire:                             "./assets/tank/tank_1/level_5_000000001010_up_fire.png",
				TankKind1 | Level5 | EquipArmor | EquipShip | MoveUp:                                     "./assets/tank/tank_1/level_5_000000001100_up.png",
				TankKind1 | Level5 | EquipArmor | EquipShip | MoveUp | Fire:                              "./assets/tank/tank_1/level_5_000000001100_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipArmor | MoveUp:                    "./assets/tank/tank_1/level_5_000000000111_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipArmor | MoveUp | Fire:             "./assets/tank/tank_1/level_5_000000000111_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipShip | MoveUp:                     "./assets/tank/tank_1/level_5_000000001011_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipShip | MoveUp | Fire:              "./assets/tank/tank_1/level_5_000000001011_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipArmor | EquipShip | MoveUp:                      "./assets/tank/tank_1/level_5_000000001101_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipArmor | EquipShip | MoveUp | Fire:               "./assets/tank/tank_1/level_5_000000001101_up_fire.png",
				TankKind1 | Level5 | EquipEngine | EquipArmor | EquipShip | MoveUp:                       "./assets/tank/tank_1/level_5_000000001110_up.png",
				TankKind1 | Level5 | EquipEngine | EquipArmor | EquipShip | MoveUp | Fire:                "./assets/tank/tank_1/level_5_000000001110_up_fire.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | MoveUp:        "./assets/tank/tank_1/level_5_000000001111_up.png",
				TankKind1 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | MoveUp | Fire: "./assets/tank/tank_1/level_5_000000001111_up_fire.png",
			},
		},
		TankKind2: {
			TankKind: "猛虎",
			KindID:   TankKind2,
			Levels: map[BaseItemID]TankLevel{
				Level1: {
					Level:      1,
					SubFrameID: Level1,
					Cooldown:   5,
					EquipSlot:  EquipMainGun,
					Hp:         25,
					Damage:     8,
					Speed:      3,
				},
				Level2: {
					Level:      2,
					SubFrameID: Level2,
					Cooldown:   5,
					EquipSlot:  EquipMainGun | EquipArmor,
					Hp:         35,
					Damage:     15,
					Speed:      4,
				},
				Level3: {
					Level:      3,
					SubFrameID: Level3,
					Cooldown:   3,
					EquipSlot:  EquipMainGun | EquipSecondGun | EquipArmor,
					Hp:         45,
					Damage:     18,
					Speed:      4,
				},
				Level4: {
					Level:      4,
					SubFrameID: Level4,
					Cooldown:   3,
					EquipSlot:  EquipMainGun | EquipSecondGun | EquipArmor,
					Hp:         55,
					Damage:     12,
					Speed:      4,
				},
				Level5: {
					Level:      5,
					SubFrameID: Level3,
					Cooldown:   2,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor | EquipShip | EquipSecondGun,
					Hp:         60,
					Damage:     15,
					Speed:      4,
				},
			},
			FrameImgs: map[BaseItemID]string{
				TankKind2 | Level1 | MoveUp:                                                                               "./assets/tank/tank_2/level_1_000000000000_up.png",
				TankKind2 | Level1 | MoveUp | Fire:                                                                        "./assets/tank/tank_2/level_1_000000000000_up_fire.png",
				TankKind2 | Level1 | EquipMainGun | MoveUp:                                                                "./assets/tank/tank_2/level_1_000000000001_up.png",
				TankKind2 | Level1 | EquipMainGun | MoveUp | Fire:                                                         "./assets/tank/tank_2/level_1_000000000001_up_fire.png",
				TankKind2 | Level2 | MoveUp:                                                                               "./assets/tank/tank_2/level_2_000000000000_up.png",
				TankKind2 | Level2 | MoveUp | Fire:                                                                        "./assets/tank/tank_2/level_2_000000000000_up_fire.png",
				TankKind2 | Level2 | EquipMainGun | MoveUp:                                                                "./assets/tank/tank_2/level_2_000000000001_up.png",
				TankKind2 | Level2 | EquipMainGun | MoveUp | Fire:                                                         "./assets/tank/tank_2/level_2_000000000001_up_fire.png",
				TankKind2 | Level2 | EquipArmor | MoveUp:                                                                  "./assets/tank/tank_2/level_2_000000000100_up.png",
				TankKind2 | Level2 | EquipArmor | MoveUp | Fire:                                                           "./assets/tank/tank_2/level_2_000000000100_up_fire.png",
				TankKind2 | Level2 | EquipMainGun | EquipArmor | MoveUp:                                                   "./assets/tank/tank_2/level_2_000000000101_up.png",
				TankKind2 | Level2 | EquipMainGun | EquipArmor | MoveUp | Fire:                                            "./assets/tank/tank_2/level_2_000000000101_up_fire.png",
				TankKind2 | Level3 | MoveUp:                                                                               "./assets/tank/tank_2/level_3_000000000000_up.png",
				TankKind2 | Level3 | MoveUp | Fire:                                                                        "./assets/tank/tank_2/level_3_000000000000_up_fire.png",
				TankKind2 | Level3 | EquipMainGun | MoveUp:                                                                "./assets/tank/tank_2/level_3_000000000001_up.png",
				TankKind2 | Level3 | EquipMainGun | MoveUp | Fire:                                                         "./assets/tank/tank_2/level_3_000000000001_up_fire.png",
				TankKind2 | Level3 | EquipSecondGun | MoveUp:                                                              "./assets/tank/tank_2/level_3_000000010000_up.png",
				TankKind2 | Level3 | EquipSecondGun | MoveUp | Fire:                                                       "./assets/tank/tank_2/level_3_000000010000_up_fire.png",
				TankKind2 | Level3 | EquipArmor | MoveUp:                                                                  "./assets/tank/tank_2/level_3_000000000100_up.png",
				TankKind2 | Level3 | EquipArmor | MoveUp | Fire:                                                           "./assets/tank/tank_2/level_3_000000000100_up_fire.png",
				TankKind2 | Level3 | EquipMainGun | EquipSecondGun | MoveUp:                                               "./assets/tank/tank_2/level_3/000000010001_up.png",
				TankKind2 | Level3 | EquipMainGun | EquipSecondGun | MoveUp | Fire:                                        "./assets/tank/tank_2/level_3/000000010001_up_fire.png",
				TankKind2 | Level3 | EquipMainGun | EquipArmor | MoveUp:                                                   "./assets/tank/tank_2/level_3/000000000101_up.png",
				TankKind2 | Level3 | EquipMainGun | EquipArmor | MoveUp | Fire:                                            "./assets/tank/tank_2/level_3/000000000101_up_fire.png",
				TankKind2 | Level3 | EquipArmor | EquipSecondGun | MoveUp:                                                 "./assets/tank/tank_2/level_3/000000010100_up.png",
				TankKind2 | Level3 | EquipArmor | EquipSecondGun | MoveUp | Fire:                                          "./assets/tank/tank_2/level_3/000000010100_up_fire.png",
				TankKind2 | Level3 | EquipMainGun | EquipSecondGun | EquipArmor | MoveUp:                                  "./assets/tank/tank_2/level_3/000000010101_up.png",
				TankKind2 | Level3 | EquipMainGun | EquipSecondGun | EquipArmor | MoveUp | Fire:                           "./assets/tank/tank_2/level_3/000000010101_up_fire.png",
				TankKind2 | Level4 | MoveUp:                                                                               "./assets/tank/tank_2/level_4/000000000000_up.png",
				TankKind2 | Level4 | MoveUp | Fire:                                                                        "./assets/tank/tank_2/level_4/000000000000_up_fire.png",
				TankKind2 | Level4 | EquipMainGun | MoveUp:                                                                "./assets/tank/tank_2/level_4/000000000001_up.png",
				TankKind2 | Level4 | EquipMainGun | MoveUp | Fire:                                                         "./assets/tank/tank_2/level_4/000000000001_up_fire.png",
				TankKind2 | Level4 | EquipSecondGun | MoveUp:                                                              "./assets/tank/tank_2/level_4/000000010000_up.png",
				TankKind2 | Level4 | EquipSecondGun | MoveUp | Fire:                                                       "./assets/tank/tank_2/level_4/000000010000_up_fire.png",
				TankKind2 | Level4 | EquipArmor | MoveUp:                                                                  "./assets/tank/tank_2/level_4/000000000100_up.png",
				TankKind2 | Level4 | EquipArmor | MoveUp | Fire:                                                           "./assets/tank/tank_2/level_4/000000000100_up_fire.png",
				TankKind2 | Level4 | EquipMainGun | EquipSecondGun | MoveUp:                                               "./assets/tank/tank_2/level_4/000000010001_up.png",
				TankKind2 | Level4 | EquipMainGun | EquipSecondGun | MoveUp | Fire:                                        "./assets/tank/tank_2/level_4/000000010001_up_fire.png",
				TankKind2 | Level4 | EquipMainGun | EquipArmor | MoveUp:                                                   "./assets/tank/tank_2/level_4/000000000101_up.png",
				TankKind2 | Level4 | EquipMainGun | EquipArmor | MoveUp | Fire:                                            "./assets/tank/tank_2/level_4/000000000101_up_fire.png",
				TankKind2 | Level4 | EquipArmor | EquipSecondGun | MoveUp:                                                 "./assets/tank/tank_2/level_4/000000010100_up.png",
				TankKind2 | Level4 | EquipArmor | EquipSecondGun | MoveUp | Fire:                                          "./assets/tank/tank_2/level_4/000000010100_up_fire.png",
				TankKind2 | Level4 | EquipMainGun | EquipSecondGun | EquipArmor | MoveUp:                                  "./assets/tank/tank_2/level_4/000000010101_up.png",
				TankKind2 | Level4 | EquipMainGun | EquipSecondGun | EquipArmor | MoveUp | Fire:                           "./assets/tank/tank_2/level_4/000000010101_up_fire.png",
				TankKind2 | Level5 | MoveUp:                                                                               "./assets/tank/tank_2/level_5/000000000000_up.png",
				TankKind2 | Level5 | MoveUp | Fire:                                                                        "./assets/tank/tank_2/level_5/000000000000_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | MoveUp:                                                                "./assets/tank/tank_2/level_5/000000000001_up.png",
				TankKind2 | Level5 | EquipMainGun | MoveUp | Fire:                                                         "./assets/tank/tank_2/level_5/000000000001_up_fire.png",
				TankKind2 | Level5 | EquipEngine | MoveUp:                                                                 "./assets/tank/tank_2/level_5/000000000010_up.png",
				TankKind2 | Level5 | EquipEngine | MoveUp | Fire:                                                          "./assets/tank/tank_2/level_5/000000000010_up_fire.png",
				TankKind2 | Level5 | EquipArmor | MoveUp:                                                                  "./assets/tank/tank_2/level_5/000000000100_up.png",
				TankKind2 | Level5 | EquipArmor | MoveUp | Fire:                                                           "./assets/tank/tank_2/level_5/000000000100_up_fire.png",
				TankKind2 | Level5 | EquipShip | MoveUp:                                                                   "./assets/tank/tank_2/level_5/000000001000_up.png",
				TankKind2 | Level5 | EquipShip | MoveUp | Fire:                                                            "./assets/tank/tank_2/level_5/000000001000_up_fire.png",
				TankKind2 | Level5 | EquipSecondGun | MoveUp:                                                              "./assets/tank/tank_2/level_5/000000010000_up.png",
				TankKind2 | Level5 | EquipSecondGun | MoveUp | Fire:                                                       "./assets/tank/tank_2/level_5/000000010000_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | MoveUp:                                                  "./assets/tank/tank_2/level_5/000000000011_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | MoveUp | Fire:                                           "./assets/tank/tank_2/level_5/000000000011_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | MoveUp:                                                   "./assets/tank/tank_2/level_5/000000000101_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | MoveUp | Fire:                                            "./assets/tank/tank_2/level_5/000000000101_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipShip | MoveUp:                                                    "./assets/tank/tank_2/level_5/000000001001_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipShip | MoveUp | Fire:                                             "./assets/tank/tank_2/level_5/000000001001_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipSecondGun | MoveUp:                                               "./assets/tank/tank_2/level_5/000000010001_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipSecondGun | MoveUp | Fire:                                        "./assets/tank/tank_2/level_5/000000010001_up_fire.png",
				TankKind2 | Level5 | EquipArmor | EquipEngine | MoveUp:                                                    "./assets/tank/tank_2/level_5/000000000110_up.png",
				TankKind2 | Level5 | EquipArmor | EquipEngine | MoveUp | Fire:                                             "./assets/tank/tank_2/level_5/000000000110_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipShip | MoveUp:                                                     "./assets/tank/tank_2/level_5/000000001010_up.png",
				TankKind2 | Level5 | EquipEngine | EquipShip | MoveUp | Fire:                                              "./assets/tank/tank_2/level_5/000000001010_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipSecondGun | MoveUp:                                                "./assets/tank/tank_2/level_5/000000010010_up.png",
				TankKind2 | Level5 | EquipEngine | EquipSecondGun | MoveUp | Fire:                                         "./assets/tank/tank_2/level_5/000000010010_up_fire.png",
				TankKind2 | Level5 | EquipArmor | EquipShip | MoveUp:                                                      "./assets/tank/tank_2/level_5/000000001100_up.png",
				TankKind2 | Level5 | EquipArmor | EquipShip | MoveUp | Fire:                                               "./assets/tank/tank_2/level_5/000000001100_up_fire.png",
				TankKind2 | Level5 | EquipArmor | EquipSecondGun | MoveUp:                                                 "./assets/tank/tank_2/level_5/000000010100_up.png",
				TankKind2 | Level5 | EquipArmor | EquipSecondGun | MoveUp | Fire:                                          "./assets/tank/tank_2/level_5/000000010100_up_fire.png",
				TankKind2 | Level5 | EquipShip | EquipSecondGun | MoveUp:                                                  "./assets/tank/tank_2/level_5/000000011000_up.png",
				TankKind2 | Level5 | EquipShip | EquipSecondGun | MoveUp | Fire:                                           "./assets/tank/tank_2/level_5/000000011000_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | MoveUp:                                     "./assets/tank/tank_2/level_5/000000000111_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | MoveUp | Fire:                              "./assets/tank/tank_2/level_5/000000000111_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipShip | MoveUp:                                      "./assets/tank/tank_2/level_5/000000001011_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipShip | MoveUp | Fire:                               "./assets/tank/tank_2/level_5/000000001011_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipSecondGun | MoveUp:                                 "./assets/tank/tank_2/level_5/000000010011_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipSecondGun | MoveUp | Fire:                          "./assets/tank/tank_2/level_5/000000010011_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipShip | MoveUp:                                       "./assets/tank/tank_2/level_5/000000001101_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipShip | MoveUp | Fire:                                "./assets/tank/tank_2/level_5/000000001101_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipSecondGun | MoveUp:                                  "./assets/tank/tank_2/level_5/000000010101_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipSecondGun | MoveUp | Fire:                           "./assets/tank/tank_2/level_5/000000010101_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipShip | EquipSecondGun | MoveUp:                                   "./assets/tank/tank_2/level_5/000000011001_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipShip | EquipSecondGun | MoveUp | Fire:                            "./assets/tank/tank_2/level_5/000000011001_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipShip | MoveUp:                                        "./assets/tank/tank_2/level_5/000000001110_up.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipShip | MoveUp | Fire:                                 "./assets/tank/tank_2/level_5/000000001110_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipSecondGun | MoveUp:                                   "./assets/tank/tank_2/level_5/000000010110_up.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipSecondGun | MoveUp | Fire:                            "./assets/tank/tank_2/level_5/000000010110_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipShip | EquipSecondGun | MoveUp:                                    "./assets/tank/tank_2/level_5/000000011010_up.png",
				TankKind2 | Level5 | EquipEngine | EquipShip | EquipSecondGun | MoveUp | Fire:                             "./assets/tank/tank_2/level_5/000000011010_up_fire.png",
				TankKind2 | Level5 | EquipArmor | EquipShip | EquipSecondGun | MoveUp:                                     "./assets/tank/tank_2/level_5/000000011100_up.png",
				TankKind2 | Level5 | EquipArmor | EquipShip | EquipSecondGun | MoveUp | Fire:                              "./assets/tank/tank_2/level_5/000000011100_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | MoveUp:                         "./assets/tank/tank_2/level_5/000000001111_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | MoveUp | Fire:                  "./assets/tank/tank_2/level_5/000000001111_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipSecondGun | MoveUp:                    "./assets/tank/tank_2/level_5/000000010111_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipSecondGun | MoveUp | Fire:             "./assets/tank/tank_2/level_5/000000010111_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipShip | EquipSecondGun | MoveUp:                     "./assets/tank/tank_2/level_5/000000011011_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipShip | EquipSecondGun | MoveUp | Fire:              "./assets/tank/tank_2/level_5/000000011011_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipShip | EquipSecondGun | MoveUp:                      "./assets/tank/tank_2/level_5/000000011101_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipArmor | EquipShip | EquipSecondGun | MoveUp | Fire:               "./assets/tank/tank_2/level_5/000000011101_up_fire.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipShip | EquipSecondGun | MoveUp:                       "./assets/tank/tank_2/level_5/000000011110_up.png",
				TankKind2 | Level5 | EquipEngine | EquipArmor | EquipShip | EquipSecondGun | MoveUp | Fire:                "./assets/tank/tank_2/level_5/000000011110_up_fire.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | EquipSecondGun | MoveUp:        "./assets/tank/tank_2/level_5/000000011111_up.png",
				TankKind2 | Level5 | EquipMainGun | EquipEngine | EquipArmor | EquipShip | EquipSecondGun | MoveUp | Fire: "./assets/tank/tank_2/level_5/000000011111_up_fire.png",
			},
		},
		TankKind3: {
			TankKind: "巨熊",
			KindID:   TankKind3,
			Levels: map[BaseItemID]TankLevel{
				Level1: {
					Level:      1,
					SubFrameID: Level1,
					Cooldown:   8,
					EquipSlot:  EquipArmor,
					Hp:         30,
					Damage:     5,
					Speed:      2,
				},
				Level2: {
					Level:      2,
					SubFrameID: Level2,
					Cooldown:   8,
					EquipSlot:  EquipMainGun | EquipArmor,
					Hp:         40,
					Damage:     8,
					Speed:      2,
				},
				Level3: {
					Level:      3,
					SubFrameID: Level3,
					Cooldown:   5,
					EquipSlot:  EquipMainGun | EquipArmor | EquipResourceCollector,
					Hp:         50,
					Damage:     30,
					Speed:      3,
				},
				Level4: {
					Level:      4,
					SubFrameID: Level4,
					Cooldown:   5,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor | EquipResourceCollector,
					Hp:         60,
					Damage:     35,
					Speed:      3,
				},
				Level5: {
					Level:      5,
					SubFrameID: Level3,
					Cooldown:   3,
					EquipSlot:  EquipMainGun | EquipEngine | EquipArmor | EquipSecondGun | EquipResourceCollector,
					Hp:         80,
					Damage:     40,
					Speed:      3,
				},
			},
		},
	}
}
